### ISSUE TITLE
Support Razzle.js

### ISSUE THREAD

**Issue by laurencefass** [agile-ts/agile#180]
### ❓ Is your feature request related to a problem? 
Next.js and Gatsby are opiononated frameworks that don't fit every use-case. 

Razzle.js is a lesser known but excellent SSR/SPA framwork allowing full freedom of implementation. Essentially it provides SSR for your CRA apps with full access to config with no eject.

https://github.com/jaredpalmer/razzle

### 📄 Describe the solution you'd like
Add support for Razzle.js

### 📃 Describe alternatives you've considered
Next.js is the dominant alternative to Razzle.js but it is very different to CRA with no plans to support React Router.

**Comment by bennodev19** [comment]
I'll see what I can do, 
because I have to figure out in general 
how to make a state management framework suitable for ssr ^^

If I get AgileTs in `Next.js` working,
it will be no problem to get it in `Razzle.js` working.

**Comment by bennodev19** [comment]
`Razzle.js` works in its basic form.. (tested in counter application)
https://github.com/agile-ts/agile/tree/develop/examples/razzle/develop/counter

However, I haven't tested it extensively yet. 
If you notice something that is not working as expected with AgileTs, 
please feel free to open an issue and report the bug.

Thanks for the support ;D
